# Generated by Django 3.0.4 on 2020-03-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='author',
            new_name='article_author',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='article_content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='title',
            new_name='article_title',
        ),
    ]
