# Generated by Django 3.0.4 on 2020-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0002_auto_20200329_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='article_body',
            field=models.TextField(default='article body'),
            preserve_default=False,
        ),
    ]
