# Generated by Django 3.0.4 on 2020-04-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0005_auto_20200422_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='article_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
