# Generated by Django 3.0.4 on 2020-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0006_auto_20200422_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
