# Generated by Django 3.0.4 on 2020-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0007_auto_20200423_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='article_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
