# Generated by Django 3.0.4 on 2020-04-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0008_content_article_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='article_content',
            new_name='article_description',
        ),
    ]
