# Generated by Django 3.0.6 on 2020-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0010_auto_20200428_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='article_image',
        ),
        migrations.AddField(
            model_name='content',
            name='article_image_link',
            field=models.TextField(default='http://hdwpro.com/wp-content/uploads/2016/12/Awesome-HD-Pic.jpg'),
            preserve_default=False,
        ),
    ]
