# Generated by Django 3.0.6 on 2020-05-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logio', '0011_auto_20200512_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='article_likes',
        ),
    ]
